//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMemory
    {
        public UserMemory()
        {
            this.UserHistories = new HashSet<UserHistory>();
        }
    
        public int User_ID { get; set; }
        public Nullable<double> Memory { get; set; }
    
        public virtual ICollection<UserHistory> UserHistories { get; set; }
    }
}
